### ISSUE TITLE
Quicktime.qts: write access violation

### ISSUE THREAD

**Issue by mrzl** [bangnoise/ofxHapPlayer#11]
Thanks a lot for this addon. I just wanted to throw in an issue I came across. I'm getting a "Quicktime.qts: write access violation" unhandled exception from time to time. There's no way for me to really reproduce it, but I was able to fix it by commenting out this line:

https://github.com/bangnoise/ofxHapPlayer/blob/master/src/ofxHapPlayer.cpp#L169

After that everything is running beautifully smooth, no memory leaks or whatsoever..

**Comment by bangnoise** [comment]
Presumably you're creating and deleting ofxHapPlayers during execution, and the exception happens during that call?

**Comment by mrzl** [comment]
Yeah, that is the case, though I couldn't really trace it down to the destructor. Is it theoretically possible to create and delete happlayers at runtime?

**Comment by bangnoise** [comment]
Yep it should be fine creating/deleting them

**Comment by bangnoise** [comment]
this issue's moot now we don't use the QuickTime library
