### ISSUE TITLE
Doesn't compile in 0.9.0 or 0.9.2

### ISSUE THREAD

**Issue by microcosm** [bangnoise/ofxHapPlayer#15]
I can successfully compile the example in 084 branch in of084. However I get the following compile errors in 090 and 092...

![screen shot 2016-02-10 at 9 17 41 pm](https://cloud.githubusercontent.com/assets/756527/12968556/8d474e84-d041-11e5-88ed-1bcd52f82daa.png)

**Comment by sheridanis** [comment]
As it says in the log hap uses the quicktime api which is 32 but and your trying to compile as 64 bit.   Try changing the target to 32 (not sure if 0.9.x supports this though) or if your on windows us the direct show hap player which supports 64bit but requires you to re- encode your hap files as avi's

**Comment by bangnoise** [comment]
closing this as dup #7

**Comment by microcosm** [comment]
Cool, switching architecture in build settings to 32 bit works for 092, thanks
