### ISSUE TITLE
update version for oFv0.9?

### ISSUE THREAD

**Issue by chankalun** [bangnoise/ofxHapPlayer#17]
Hello,
I would like to use the addon for one of my projects, and would like to ask if there will be an update version for oF v0.9 please?
Cheers,
Karen

**Comment by bangnoise** [comment]
what platform are you on?

**Comment by chankalun** [comment]
xCode 7.2.1 :))) I would also like to ask if there will be documentation about how to close(); stop(); getCurrentFrame(); and getTotalNumFrames(); please? x

**Comment by bangnoise** [comment]
Set your build to 32-bit, not 64. Currently we rely on QuickTime, which is 32-bit only.

Those functions you ask about seem fairly obviously named. What questions do you have about them?

**Comment by chankalun** [comment]
Cos I tried to use them but they are not functioning... Hence, I wonder if you have those functions on ofxHapPlayer as well x

**Comment by chankalun** [comment]
oh I got it working now :))) x
