### ISSUE TITLE
i have 2 questions

### ISSUE THREAD

**Issue by UnivateBV** [bangnoise/ofxHapPlayer#21]
The first one, i try to load a hapq video and it doesnt load. A normal hap movie is playing fine. Do i miss something? 
The second question is, i could get it running on mac os 10.11 and with of 090 but i need hapq in a 093 project. I got a lot of Linker errors. I also tried to change build settings to 32bit without success.

**Comment by bangnoise** [comment]
2 questions should be 2 issues please.

093 OF is broken for 32-bit (openFrameworks/openFrameworks#4993). Use 092 or 094 RC.

Hap Q should play (Hap Q Alpha isn't supported yet). Please open a new issue for that with more details of the problem.

**Comment by bangnoise** [comment]
Closing this, please open a new issue if you still have problems with Hap Q video
