### ISSUE TITLE
libavformat,   av_packet_XXX was not declared error

### ISSUE THREAD

**Issue by getarobo** [bangnoise/ofxHapPlayer#23]
Hi I'm Gene from FakeLove.

I am running into issue with libavformat. Trying to run(make) example in libavformat branch and I am getting some errors:
`
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In member function ‘void ofxHap::PacketCache::store(AVPacket*)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:49:44: error: ‘av_packet_alloc’ was not declared in this scope
         AVPacket *packet = av_packet_alloc();
                                            ^

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In member function ‘void ofxHap::PacketCache::cache()’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:68:30: error: ‘av_packet_free’ was not declared in this scope
             av_packet_free(&p);
                              ^/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In member function ‘void ofxHap::PacketCache::store(AVPacket*)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:49:44: error: ‘av_packet_alloc’ was not declared in this scope
         AVPacket *packet = av_packet_alloc();
                                            ^

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In member function ‘void ofxHap::PacketCache::cache()’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:68:30: error: ‘av_packet_free’ was not declared in this scope
             av_packet_free(&p);
                              ^

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static bool ofxHap::PacketCache::fetch(const std::map<long unsigned int, AVPacket*>&, uint64_t, AVPacket*)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:113:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (pair.second->pts <= pts && pair.second->pts + pair.second->duration > pts)
                              ^

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:113:81: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (pair.second->pts <= pts && pair.second->pts + pair.second->duration > pts)
                                                                                 ^
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static void ofxHap::PacketCache::limit(std::map<long unsigned int, AVPacket*>&, const ofxHap::TimeRangeSet&, bool)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:145:30: error: ‘av_packet_free’ was not declared in this scope
             av_packet_free(&p);
                              ^

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static void ofxHap::PacketCache::clear(std::map<long unsigned int, AVPacket*>&)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:159:36: error: ‘av_packet_free’ was not declared in this scope
         av_packet_free(&pair.second);

/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static bool ofxHap::PacketCache::fetch(const std::map<long unsigned int, AVPacket*>&, uint64_t, AVPacket*)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:113:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (pair.second->pts <= pts && pair.second->pts + pair.second->duration > pts)
                              ^
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:113:81: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (pair.second->pts <= pts && pair.second->pts + pair.second->duration > pts)
                                                                                 ^
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static void ofxHap::PacketCache::limit(std::map<long unsigned int, AVPacket*>&, const ofxHap::TimeRangeSet&, bool)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:145:30: error: ‘av_packet_free’ was not declared in this scope
             av_packet_free(&p);
                              ^
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp: In static member function ‘static void ofxHap::PacketCache::clear(std::map<long unsigned int, AVPacket*>&)’:
/home/fakelinux/Documents/of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/ofxHap/src/PacketCache.cpp:159:36: error: ‘av_packet_free’ was not declared in this scope
         av_packet_free(&pair.second);
`

My system setting is
ubuntu 16.05 LTS
openframeworks v0.9.8_linux64_release

I have ran linux instructions before hand.

Any ideas?

Thank you!

**Comment by bangnoise** [comment]
Ah I'm on Ubuntu 16.10 (the non LTS version), which has a more recent version of libavcodec.

Try pulling my latest commit - there may be other missing functions, let me know.

**Comment by getarobo** [comment]
awesome~ working now!
git pull did it.

**Comment by bangnoise** [comment]
New requirement for Linux is libdispatch, to support multithreaded decoding when frames are chunked. I've updated the README, but basically:

`sudo apt-get install libdispatch-devel`

**Comment by gustavonecore** [comment]
@bangnoise Actually... the lib name is `libdispatch-dev` instead of `devel` at the end.. this took me like 10 minutes to realize haha.
