### ISSUE TITLE
Build error in HapSupport.h. Line: "#include <QuickTime/QuickTime.h>"

### ISSUE THREAD

**Issue by corybarr** [bangnoise/ofxHapPlayer#34]
Hello.

It's been a couple of years since I used this add-on, but remember really liking it. I'm trying it again. At compile time, I get the error 'QuickTime/QuickTime.h' file not found. I'm on Xcode 8.3.3 and macOS 10.12.

Any suggestions?

Thanks.

**Comment by corybarr** [comment]
I was able to get around the issue by downloading the OS X 10.11 SDK, dropping it in Xcode's SDK folder, and changing the base SDK for the example project. I'm not positive the best way to implement a permanent solution. Bundle the OS X 10.11 SDK with this add-on? I believe the QuickTime frameworks was removed from Xcode.

**Comment by bangnoise** [comment]
Try the libavformat branch - it isn't quite feature-complete, but mostly works fine, without QuickTime issues

**Comment by chao-mu** [comment]
Are there plans to merge the libavformat into master?

**Comment by bangnoise** [comment]
@chao-mu yes - just not sure when. Requires some work on handling audio.

**Comment by chao-mu** [comment]
I noticed this was closed - does that mean it's fixed?

**Comment by bangnoise** [comment]
libavformat has been merged into master - no QuickTime dependency any more
