### ISSUE TITLE
Snappy version incompatibility. Update in bundle?

### ISSUE THREAD

**Issue by dmelladom** [bangnoise/ofxHapPlayer#37]
Hello!
I am using the libav branch, OSX 10.12.
It compiles but crashes right after execution with this message:
dyld: Library not loaded: @rpath/snappy/lib/osx/libsnappy.1.dylib
  Referenced from: /Developer/of_v0.9.8_osx_release/apps/myApps/Cannula_Munich64/bin/Cannula_Munich64Debug.app/Contents/MacOS/Cannula_Munich64Debug
  Reason: Incompatible library version: Cannula_Munich64Debug requires version 5.0.0 or later, but libsnappy.1.dylib provides version 1.0.0

It is my understanding that the included snappy lib in the bundle is version 1. Is there anyway to update the version in the bundle?

Thanks!

**Comment by bangnoise** [comment]
Did you use the OF Project Generator to make your project? Sounds like a misconfiguration.

**Comment by dmelladom** [comment]
Yes, I did. Is there any thign I can try to reconfigure?


2017-10-19 11:39 GMT+02:00 Tom Butterworth <notifications@github.com>:

**Comment by bangnoise** [comment]
Do you have snappy installed on your system elsewhere, eg through Homebrew or MacPorts? Might be that an older version is being picked up instead of the bundled version.

**Comment by bangnoise** [comment]
Perhaps you could paste the output of

````otool -L /Developer/of_v0.9.8_osx_release/apps/myApps/Cannula_Munich64/bin/Cannula_Munich64Debug.app/Contents/MacOS/Cannula_Munich64Debug````

**Comment by dmelladom** [comment]
/Developer/of_v0.9.8_osx_release/apps/myApps/Cannula_Munich64/bin/Cannula_Munich64Debug.app/Contents/MacOS/Cannula_Munich64Debug:
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
(compatibility version 1.0.0, current version 4.0.0)
    /System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility
version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
(compatibility version 45.0.0, current version 1504.82.104)

/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
(compatibility version 1.0.0, current version 48.0.0)

/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
(compatibility version 1.0.0, current version 492.0.0)

/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
(compatibility version 1.0.0, current version 2.0.0)
    /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
(compatibility version 1.0.0, current version 22.0.0)
    /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
(compatibility version 1.0.0, current version 1.0.0)

/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
(compatibility version 150.0.0, current version 1349.64.0)
    /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
(compatibility version 1.0.0, current version 1.0.0)

/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
(compatibility version 1.0.0, current version 775.19.0)
    /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
(compatibility version 1.2.0, current version 1.5.0)
    /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
(compatibility version 1.0.0, current version 275.0.0)
    /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
(compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
(compatibility version 1.2.0, current version 1.11.0)
    /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
(compatibility version 1.0.0, current version 1.0.0)
    @executable_path/../Frameworks/GLUT.framework/Versions/A/GLUT
(compatibility version 1.0.0, current version 1.0.0)
    @executable_path/../Frameworks/libfmodex.dylib (compatibility version
1.0.0, current version 1.0.0)
    @rpath/ffmpeg/lib/osx/libavcodec.57.dylib (compatibility version
57.0.0, current version 57.64.101)
    @rpath/ffmpeg/lib/osx/libavformat.57.dylib (compatibility version
57.0.0, current version 57.56.101)
    @rpath/ffmpeg/lib/osx/libavutil.55.dylib (compatibility version 55.0.0,
current version 55.34.101)
    @rpath/ffmpeg/lib/osx/libswresample.2.dylib (compatibility version
2.0.0, current version 2.3.100)
    @rpath/snappy/lib/osx/libsnappy.1.dylib (compatibility version 5.0.0,
current version 5.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version
307.5.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current
version 1238.50.2)
    /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
(compatibility version 300.0.0, current version 1349.63.0)
    /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version
228.0.0)

2017-10-19 12:28 GMT+02:00 Tom Butterworth <notifications@github.com>:

**Comment by vertexcite** [comment]
Try use an older version of `snappy`, e.g. 1.1.4

**Comment by bangnoise** [comment]
Closing this as it's an old issue, please comment if you still hit it using the latest on the master branch.
