### ISSUE TITLE
C2733 - 'GetProcessInformation': second C linkage of overloaded function not allowed

### ISSUE THREAD

**Issue by OnkelDittmeyer** [bangnoise/ofxHapPlayer#38]
Im getting the referenced error message when compiling the library within a 0.9.8 OF project.
The function throwing the error is within the windows quicktime version  6.0.2,  process.h

`EXTERN_API( OSErr )
GetProcessInformation           (const ProcessSerialNumber * PSN, 
                                 ProcessInfoRec *       info)                               THREEWORDINLINE(0x3F3C, 0x003A, 0xA88F);
`

**Comment by bangnoise** [comment]
The current release removes the reliance on QuickTime.
