### ISSUE TITLE
Error compiling on Ubuntu 64bit

### ISSUE THREAD

**Issue by PTS93** [bangnoise/ofxHapPlayer#39]
The limitation of the QuickTime 32bit library makes it not possible to compile the example on Ubuntu 17.10 (only has a 64bit release).
So I have to use the x64 version of OF 0.9.8. 
First two errors of a long chain of errors I get:
```
../of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/HapSupport/src/HapSupport.h:41:2: error: #error Hap QuickTime support requires 32-bit QuickTime APIs but this target is 64-bit
 #error Hap QuickTime support requires 32-bit QuickTime APIs but this target is 64-bit
  ^~~~~
../of_v0.9.8_linux64_release/addons/ofxHapPlayer/libs/HapSupport/src/HapSupport.c:35:10: fatal error: Windows.h: No such file or directory
 #include <Windows.h>

```
I tried out the other branches but no success with those either, throwing the same errors.

**Comment by bangnoise** [comment]
Use the libavformat branch. Re-open this issue if that doesn't solve it.

**Comment by PTS93** [comment]
Ok seems like there went something wrong when I did a checkout to the other branches, after deleting and cloning again directly the libavformat branch instead of the master branch and then switching it is all working.
