### ISSUE TITLE
hap-alpha 

### ISSUE THREAD

**Issue by Kj1** [bangnoise/ofxHapPlayer#4]
Hi,
i've got some issues with HAP-alpha video's that do not play correctly:
- Alpha channel is not displayed correctly 
- setPosition/frame show weird behavior

Recoded the video in hap regular and it worked correctly.

(using 084, vs2012 & Hap QuickTime Codec version 6)

Thanks!

**Comment by dmelladom** [comment]
Hi! I am having no problems at all, working with 30 clips at the same time. Would you share your code?
What do you mean by Alpha channel not working correctly? I have noticed that some software does not correctly export alpha channel (it makes it solid black) when encoding to Hap5. Using After Effects works OK to me.

**Comment by Kj1** [comment]
Using adobe media encoder, but it might be a transcoding issue.  I'll give it a go in AE!
I'm using the original example but with a different movie.

**Comment by dmelladom** [comment]
Precisely AME gave me problems ;)
Give it a try in AE, it works like a charm. Also QTPro works fine.
About your problems with setPosition and frame, I used the example and worked ok. Remember that in the draw method you set the position again.

**Comment by Kj1** [comment]
you're right, exporting from AE worked perfectly!  Thanks for the tip!

**Comment by bangnoise** [comment]
Hi, if either of you are having problems exporting Hap alpha from AME then it would be good if you could [open an issue for the codec](https://github.com/Vidvox/hap-qt-codec/issues) - just make sure you've set the depth to 32-bit in AME.

**Comment by chankalun** [comment]
Hello, I am using AE but I couldn't play my video... may I ask if there is anything specifically to change in AE to export the file apart from changing the channel to RGB+Alpha please?
Also, I am not able to play the sample video as well...
Cheers,
Karen

**Comment by bangnoise** [comment]
@chankalun Something's up if you can't play the sample, have you installed the QuickTime codec? it's required. https://github.com/Vidvox/hap-qt-codec/releases/latest
