### ISSUE TITLE
how's the dev state for 0.9.8 / Windows 10, VS 2015?

### ISSUE THREAD

**Issue by moebiussurfing** [bangnoise/ofxHapPlayer#40]
I would like to know what's the best chance to use the addon on Windows...

What about to use this other one: https://github.com/secondstory/ofxWMFVideoPlayer
Should be the best Windows alternative? or it's much slow...? 

What I need is to play dual screen full hd, 3840x1080

**Comment by bangnoise** [comment]
The libavformat branch works on 0.9.8/Windows
