### ISSUE TITLE
libavformat branch: Need to check example projects for OF 0.10

### ISSUE THREAD

**Issue by agness** [bangnoise/ofxHapPlayer#42]
<img width="555" alt="screen shot 2018-05-25 at 2 54 28 pm" src="https://user-images.githubusercontent.com/253081/40561685-0c5f80a2-602c-11e8-8924-5f0a66b3ed0a.png">

I've tried cleaning build folder and removing derived data, and neither works. Any suggestions?

OF v0.10.0
macOS 10.13.4
XCode 9.3.1

**Comment by agness** [comment]
I solved this by downloading [OF 0.9.8](https://github.com/openframeworks/openFrameworks/releases), and copying over the missing `../../../libs/glut/lib/osx/GLUT.framework" failed: No such file or directory (2)`

All is well:
![screen shot 2018-05-25 at 3 29 13 pm](https://user-images.githubusercontent.com/253081/40562785-675ee32c-6030-11e8-9517-5be92442a349.png)

**Comment by bangnoise** [comment]
Thanks for alerting me - if you pull the latest revision the Xcode project is updated for OF 0.10 - no need for GLUT.framework

**Comment by bangnoise** [comment]
(reopening this until I check Windows & Linux)
