### ISSUE TITLE
Multiple players in OpenGL 3+ doesn't work

### ISSUE THREAD

**Issue by pixelsandcandy** [bangnoise/ofxHapPlayer#47]
Tried of_v0.9.8 (**libavformat-OF-0.9** branch) and of_v0.10.0 (**master** branch)

**Setup**
- MacOS High Sierra (10.13.6)
- Xcode 10.1 / 9.4.1
- Xcode: Base SDK - OS X 10.11 (libavformat-OF-0.9 branch)
- Xcode: Base SDK - macOS 10.13 (master branch)

**Works**
- Project Generator > add ofxHapPlayer > load / update / draw (**first video works**)
- Add second ofxHapPlayer (**different video**) > load / update / draw (**both videos work**)

**Doesn't work**
- Change OpenGL to 3.2 (**first video works, second renders black**)

---

I'm going to look into this but posting here in case anyone has run into this and can help. Thanks!

---

`(main.cpp)`

`ofGLWindowSettings settings;`
`settings.glVersionMajor = 3;`
`settings.glVersionMinor = 2;`
`ofCreateWindow(settings);`

`ofRunApp(new ofApp());`

**Comment by BenBergman** [comment]
I'm experiencing this issue too. I'm also unable to load a different video file into the original player. This just renders as black.

@pixelsandcandy Which opengl version did work for you to play multiple files? Any version of 2.x I've tried is rendering everything as a white screen for me.

**Comment by bangnoise** [comment]
The original issue as reported by @pixelsandcandy should be fixed now on master. Please re-open this issue if not.

@BenBergman I suspect you're hitting a different issue - please pull the latest on master and open a new issue with more details if it persists.
