### ISSUE TITLE
[question] how to get the player current time? 

### ISSUE THREAD

**Issue by moebiussurfing** [bangnoise/ofxHapPlayer#54]
I am looking for a  'player.getCurrentTime()' method...
I want to show current video time like any video player app, 
independent of the speed or framerate... 

Any idea?

I have seen player.getCurrentFrame() and player.getTotalNumFrames(), but they are not implemented.

Maybe the only way is to get the player position (0.0 to 1.0) and then make some map from 0 to video duration? 

I am in macOS, OF 0.10

**Comment by moebiussurfing** [comment]
I am using this workaround for the momment:
```
void ofApp::update()
{
    POSITION = player.getPosition();//float

    float currDur, prcPos;
    currDur = player.getDuration();
    prcPos = currDur * POSITION;//current time in seconds?
    int currMin, currSec;
    currMin = prcPos / 60;
    currSec = ((int)(prcPos)) % 60;
    string strMin, strSec;
    strMin = (currMin < 10) ? "0" : "";
    strSec = (currSec < 10) ? "0" : "";
    strMin+= ofToString(currMin);
    strSec+= ofToString(currSec);

    videoTIME = strMin + ":" + strSec;//string

...
}
```

**Comment by bangnoise** [comment]
Yes, your "workaround" is the answer to your question: use `getPosition() * getDuration()`.
