### ISSUE TITLE
Hap Alpha video can look through

### ISSUE THREAD

**Issue by UnivateBV** [bangnoise/ofxHapPlayer#55]
I use a hap alpha video with transparency, but on not transparent parts i can look throug it. It looks like it has 5% global transparency. Do you have any ideas?
Thanks

**Comment by bangnoise** [comment]
The currently set color applies to drawing - try ofSetColor(255, 255, 255) before you draw?

**Comment by UnivateBV** [comment]
Yes, i have ofSetColor(255) before the player drawing command. But i can see the image i draw before the ofSetColor. I dont think that there is a difference in ofSetColor(255) vs ofSetColor(255,255,255)

**Comment by bangnoise** [comment]
Do you see the problem if you play the same file using the example app in ofxHapPlayer/example?

**Comment by UnivateBV** [comment]
Yes i tested it now with the example app and still the same. But it is solved. The designer made a mistake with the alpha channel, he used 250 instead of 255. Sorry for this troubble.  :(
But big thanks for your patience. :)
