### ISSUE TITLE
ofTexture problems

### ISSUE THREAD

**Issue by dmelladom** [bangnoise/ofxHapPlayer#6]
Hi!
I am trying to apply a shader to a texture from a Hap clip.
ofxHapPlayer player;
ofTexture tex;

setup()
----------
player.loadMovie("test.mov");
player.play();

update()
---------
tex = *player.getTexture();

draw()
----------
tex.draw(0,0).

That works OK, but when I set tax.draw() inside a shader.begin()/shader.end() block it does not.
Using ofVideoPlayer and getTextureReference (without *) works OK. Any idea?

Edit: I can bypass it drawing to a FBO first, but doesn't look like a neat solution.

My shader is really dummy, does nothing...
.vert
#version 120
#extension GL_ARB_texture_rectangle : enable
#extension GL_EXT_gpu_shader4 : enable
void main() {
    gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
    gl_TexCoord[0] = gl_MultiTexCoord0;
    gl_FrontColor = gl_Color;
}

.frag

#version 120
#extension GL_ARB_texture_rectangle : enable
#extension GL_EXT_gpu_shader4 : enable

uniform sampler2DRect texture0;

uniform float time;

void main(){
    vec2 pos = gl_TexCoord[0].xy;
    vec4 color = texture2DRect(texture0, pos);
    gl_FragColor = color;

}

**Comment by bangnoise** [comment]
The texture target is `GL_TEXTURE_2D`, not `GL_TEXTURE_RECTANGLE_ARB`. Change your shader to use a 2D sampler.

I'm closing this issue but reopen it if you hit any further problems.
