### ISSUE TITLE
Ringerbuffer clashes with ofxIO

### ISSUE THREAD

**Issue by stephanschulz** [bangnoise/ofxHapPlayer#61]
I know too little about the inner workings of your addon and the ofxIO addon, but when using both together Ringbuffer.h reports compile problems.
I am sure it's just some simple change I would need to add to make each add-on's ring buffer implementation not see each other. But don't know how.
So I went ahead and renamed yours to ringbufferHap, which made it all work.

**Comment by oscarwyatt** [comment]
If you delete (or remove references to) the `brotli` folder in `ofxIO/libs/ ` it will compile (not certain it runs yet but well worth a go, I seem to remember this from a while back). If it works I'll try and remember to raise a PR amending the readme

**Comment by bangnoise** [comment]
Thanks for the report - fixed
