### ISSUE TITLE
Sending video images to ofxCv

### ISSUE THREAD

**Issue by tedmoore** [bangnoise/ofxHapPlayer#65]
Greetings,

Thanks for this great addon! Is there a way to get these images to interface nicely with ofxCv and/or ofxOpenCv? I'm having trouble getting them to work, mostly because I can't ```.getPixels()```. Is there a way to get the pixels from the ```.getTexture()```?

Thank you,

T

**Comment by bangnoise** [comment]
I haven't used ofxCv or ofxOpenCv, but if they require memory access via getPixels() then you'll have to copy to another texture via an FBO, then getPixels on the copied-to texture.
