### ISSUE TITLE
getTotalNumFrames() returns 0

### ISSUE THREAD

**Issue by fred-dev** [bangnoise/ofxHapPlayer#67]
After loading a video getTotalNumFrames() always returns 0, so does getDuration().
This is using OF 0.11.2 and OSX 10.15.7 (19H15).

**Comment by bangnoise** [comment]
Does this happen with the example project/media?
If not, please provide sample media which replicates this issue.

**Comment by fred-dev** [comment]
Yes for me this is happening with the included sample media.

**Comment by bangnoise** [comment]
When you say "after loading", do you mean after `load()` returns? Loading is asynchronous - you won't get valid values until `isLoaded()` returns true. Is that the problem?

**Comment by fred-dev** [comment]
Aha, yes you are correct, after isLoaded() returns true I can get the values. I will close this issue and the related getWidth() issue.
