### ISSUE TITLE
getWidth() and getHeight() return 0

### ISSUE THREAD

**Issue by fred-dev** [bangnoise/ofxHapPlayer#68]
After loading getWidth() and getHeight() return 0.
Using OF 0.11.2 and OSX 10.15.7 (19H15).

**Comment by bangnoise** [comment]
Presumably related to #67 - awaiting feedback there

**Comment by fred-dev** [comment]
This needed for me to wait until isLoaded() returned true (see https://github.com/bangnoise/ofxHapPlayer/issues/67) and functions correctly.
