### ISSUE TITLE
AVFoundation-based player?

### ISSUE THREAD

**Issue by mattfelsen** [bangnoise/ofxHapPlayer#7]
Not really an issue per se, but more of a question: have you done any work on, or know of anyone who's been tackling, an AVFoundation-based Hap player for OF?

**Comment by bangnoise** [comment]
No but would welcome a pull request. https://github.com/Vidvox/hap-in-avfoundation would be a useful start.

**Comment by mattfelsen** [comment]
Thanks for the quick reply. Yes, I've been looking through the test app code but I'm a little out of my element here :open_mouth:

**Comment by bangnoise** [comment]
Going to leave this open because it will have to happen before OF 0.9, cheers

**Comment by mattfelsen** [comment]
Ah sorry, didn't mean to jump the gun 👍

**Comment by DomAmato** [comment]
This is also relevant to OF0.9 for the 64 bit updates to windows. There appears to be a direct show version so that it is no longer stuck at 32 bit due to quicktime limitations

**Comment by bangnoise** [comment]
pull requests for Windows or OS X are very welcome

**Comment by DomAmato** [comment]
@bangnoise I know you might not have had any direct involvement with the directshow codec development so im asking more to get a better understanding of how the addon works. Is there more to it than updating the texture and shaders when there is a new frame? My hunch is to port the ofDirectShowVideoPlayer in the ofcore and alter the functions to incorporate this methodology but I figure better to get it straight from the horses mouth incase there is something I'm missing.

**Comment by bangnoise** [comment]
@DomAmato I've just looked over the DS codec and ofDirectShowVideoPlayer and yep, this seems a good direction - avoiding the conversion to RGB step that ofDirectShowVideoPlayer does, obviously. I don't know much at all about DirectShow playback, so I may be missing all sorts of obvious things...

**Comment by DomAmato** [comment]
so the guys over at second story beat me to it,

https://github.com/secondstory/ofxDSHapVideoPlayer

 I will port this over so that things can be in one addon

**Comment by bangnoise** [comment]
that would be amazing 👍

**Comment by dmelladom** [comment]
Hi! Is there any news on this into v0.9.0? It would be amazing to have this add on into 64bits and being able to load videos asynchronously!
Thanks!
D!

**Comment by bangnoise** [comment]
no news, pull requests welcome

**Comment by bangnoise** [comment]
cf https://github.com/gameoverhack/ofxHAPAVPlayer

**Comment by bangnoise** [comment]
Going to start work on an AVFoundation version for OSX soon

**Comment by sheridanis** [comment]
That would be awesome

**Comment by bangnoise** [comment]
Closing this, see the libavformat branch (which will be merged to master soonish)
