### ISSUE TITLE
"HapSupport.c error: 'true' undeclared" in Code::Blocks

### ISSUE THREAD

**Issue by michaelbaisch** [bangnoise/ofxHapPlayer#8]
While compiling in Code::Blocks I get: 

```
HapSupport.c 66 error: 'false' undeclared (first use in this function)
HapSupport.c 70 error: 'true' undeclared (first use in this function)
...
```

I fixed it for me by adding `#include <stdbool.h>` here:

```
#if defined(__APPLE__)
#define HAP_BZERO(x,y) bzero((x),(y))
#else
#define WINVER 0x0600
#define _WIN32_WINNT 0x0600
#include <Windows.h>
#include <stdbool.h>
#define HAP_BZERO(x,y) ZeroMemory((x),(y))
#endif
```

**Comment by bangnoise** [comment]
Thanks for the report - a check for Code::Blocks will be required because the extra include doesn't work with Visual Studio 2012. A pull request welcome, or I'll get to it eventually...

**Comment by smtabatabaie** [comment]
I'm also getting this error with Code Blocks , is it something related to not having codecs or something?
I'm getting it on this function in HapSupport.cc on line 65
static Boolean HapQTCodecIsAvailable(OSType codecType)
{
    CodecNameSpecListPtr list;
    OSStatus error;
    short i;
    
    error = GetCodecNameList(&list, 0);
    if (error) return false;
    
    for (i = 0; i < list->count; i++ )
    {        
        if (list->list[i].cType == codecType) return true;
    }
    
    return false;
}

**Comment by smtabatabaie** [comment]
replacing "true" with 1 and "false" with 0 seems to work

**Comment by bangnoise** [comment]
closing this as Code::Blocks is no longer supported by OF
